language: rust
rust: 1.34.1
sudo: true
cache:
  timeout: 1024
  directories:
    - $HOME/.cargo

if: "branch = master OR type != push OR fork = true OR tag =~ ^v"

env:
  global:
    - RUST_BACKTRACE=full

matrix:
  include:
    - os: osx
    - os: linux

install:
  - make ci-install

script:
  - make ci

before_cache:
  - rm -rf $HOME/.cargo/registry
